"""init schema

Revision ID: 1cae0861320d
Revises: 
Create Date: 2026-07-15 13:45:21.003255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cae0861320d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('draft', 'active', 'closed', name='eventstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('kakao_template_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('winner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('discord_id', sa.String(length=200), nullable=True),
    sa.Column('slack_webhook', sa.String(length=200), nullable=True),
    sa.Column('source', sa.Enum('csv', 'manual', name='winnersource'), nullable=False),
    sa.Column('is_winner', sa.Boolean(), nullable=False),
    sa.Column('selected_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('winner_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.Enum('kakao', 'sms', 'email', 'webhook', name='channel'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'success', 'failed', name='messagestatus'), nullable=False),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['winner_id'], ['winner.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('redemption',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('winner_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('prize_name', sa.String(length=200), nullable=False),
    sa.Column('gift_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('issued', 'redeemed', 'expired', name='redemptionstatus'), nullable=False),
    sa.Column('issued_at', sa.DateTime(), nullable=True),
    sa.Column('redeemed_at', sa.DateTime(), nullable=True),
    sa.Column('redeemed_by', sa.String(length=100), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['winner_id'], ['winner.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('token'),
    sa.UniqueConstraint('winner_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('redemption')
    op.drop_table('message_log')
    op.drop_table('winner')
    op.drop_table('message_template')
    op.drop_table('event')
    op.drop_table('admin')
    # ### end Alembic commands ###
