"""add gift_code to redemption

Revision ID: c0af989c385e
Revises: 1cae0861320d
Create Date: 2026-07-15 14:24:08.079561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0af989c385e'
down_revision: Union[str, Sequence[str], None] = '1cae0861320d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('redemption', sa.Column('gift_code', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('redemption', 'gift_code')
    # ### end Alembic commands ###
